Repository course-maker/Course-Maker-BE, pull requests merged in 2024-07, with the labels that each got.

#178 Fix: tourApi 데이터 요청 멀티쓰레드로 변경으로 인한 데이터 불러오는 속도 향상
  src/main/java/coursemaker/coursemaker/CoursemakerApplication.java
  src/main/java/coursemaker/coursemaker/api/tourApi/controller/TourApiController.java
  src/main/java/coursemaker/coursemaker/api/tourApi/dto/TourApiResponse.java
  src/main/java/coursemaker/coursemaker/api/tourApi/service/TourApiService.java
  src/main/java/coursemaker/coursemaker/api/tourApi/service/TourApiServiceImpl.java
Labels: Refactor

#181 #157 #158 Feat: 로그인 로직 개발
  build.gradle
  src/main/java/coursemaker/coursemaker/StubData.java
  src/main/java/coursemaker/coursemaker/config/SecurityConfig.java
  src/main/java/coursemaker/coursemaker/domain/auth/controller/AuthController.java
  src/main/java/coursemaker/coursemaker/domain/auth/dto/CustomMemberDetails.java
  src/main/java/coursemaker/coursemaker/domain/auth/dto/LoginResponseDto.java
  src/main/java/coursemaker/coursemaker/domain/auth/exception/InvalidPasswordException.java
  src/main/java/coursemaker/coursemaker/domain/auth/exception/UnAuthorizedException.java
  src/main/java/coursemaker/coursemaker/domain/auth/filter/EmailLoginFilter.java
  src/main/java/coursemaker/coursemaker/domain/auth/filter/ExceptionHandlerFilter.java
  src/main/java/coursemaker/coursemaker/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/coursemaker/coursemaker/domain/auth/jwt/JwtProvider.java
  src/main/java/coursemaker/coursemaker/domain/auth/service/AuthService.java
  src/main/java/coursemaker/coursemaker/domain/member/controller/MemberApiController.java
  src/main/java/coursemaker/coursemaker/domain/member/exception/UnauthorizedException.java
  src/main/java/coursemaker/coursemaker/domain/member/exception/UserNotFoundException.java
  src/main/java/coursemaker/coursemaker/domain/member/service/MemberService.java
  src/main/java/coursemaker/coursemaker/domain/tag/controller/TagController.java
  src/main/java/coursemaker/coursemaker/exception/GlobalExceptionHandler.java
  src/main/java/coursemaker/coursemaker/exception/RootException.java
  src/main/java/coursemaker/coursemaker/util/LoginUserArgumentResolver.java
Labels: Feat

#183 Refactor: [Auth] 스웨거용 더미 로그인 컨트롤러 제작
  build.gradle
  src/main/java/coursemaker/coursemaker/domain/auth/controller/AuthController.java
Labels: Docs

#184 #157 Feat: [Auth] 토큰 검증 로직 제작
  src/main/java/coursemaker/coursemaker/config/SecurityConfig.java
  src/main/java/coursemaker/coursemaker/domain/auth/exception/ExpiredTokenException.java
  src/main/java/coursemaker/coursemaker/domain/auth/exception/InvalidTokenException.java
  src/main/java/coursemaker/coursemaker/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/coursemaker/coursemaker/domain/auth/jwt/JwtProvider.java
  src/main/java/coursemaker/coursemaker/domain/auth/jwt/TokenType.java
  src/main/java/coursemaker/coursemaker/exception/ErrorCode.java
Labels: Feat

#185 #157 Feat: [Auth] 토큰 변조 감지 로직 추가
  src/main/java/coursemaker/coursemaker/domain/auth/filter/ExceptionHandlerFilter.java
  src/main/java/coursemaker/coursemaker/domain/tag/controller/TagController.java
  src/main/java/coursemaker/coursemaker/exception/ErrorCode.java
  src/main/java/coursemaker/coursemaker/exception/RootException.java
Labels: Feat

#186 tourapi
  build.gradle
  src/main/java/coursemaker/coursemaker/CoursemakerApplication.java
  src/main/java/coursemaker/coursemaker/api/tourApi/controller/TourApiController.java
  src/main/java/coursemaker/coursemaker/api/tourApi/dto/TourApiResponse.java
  src/main/java/coursemaker/coursemaker/api/tourApi/entity/TourApi.java
  src/main/java/coursemaker/coursemaker/api/tourApi/service/TourApiService.java
  src/main/java/coursemaker/coursemaker/api/tourApi/service/TourApiServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/course/controller/CourseApiController.java
  src/main/java/coursemaker/coursemaker/domain/course/repository/TravelCourseRepository.java
  src/main/java/coursemaker/coursemaker/domain/course/service/CourseService.java
  src/main/java/coursemaker/coursemaker/domain/course/service/CourseServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/destination/entity/Destination.java
Labels: Refactor

#192 TourApi 음식점 필터링 및 무장애 여부 Destination DB에 추가
  src/main/java/coursemaker/coursemaker/api/busanApi/service/BusanApiService.java
  src/main/java/coursemaker/coursemaker/api/busanApi/service/BusanApiServiceImpl.java
  src/main/java/coursemaker/coursemaker/api/tourApi/service/TourApiServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/destination/dto/DestinationDto.java
  src/main/java/coursemaker/coursemaker/domain/destination/dto/RequestDto.java
  src/main/java/coursemaker/coursemaker/domain/destination/entity/Destination.java
  src/main/java/coursemaker/coursemaker/domain/destination/repository/DestinationRepository.java
Labels: Feat
