Repository course-maker/Course-Maker-BE, pull requests merged in 2024-09, with the labels that each got.

#291 Refactor: ike, wish, review를 유니크로 바꾸고, 코스 도메인과 공공데이터 도메인 로그 작성
  src/main/java/coursemaker/coursemaker/api/tourApi/service/TourApiServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/course/service/CourseServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/like/entity/CourseLike.java
  src/main/java/coursemaker/coursemaker/domain/like/entity/DestinationLike.java
  src/main/java/coursemaker/coursemaker/domain/like/service/CourseLikeServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/like/service/DestinationLikeServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/review/entity/CourseReview.java
  src/main/java/coursemaker/coursemaker/domain/review/entity/DestinationReview.java
  src/main/java/coursemaker/coursemaker/domain/review/service/CourseReviewServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/review/service/DestinationReviewServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/wish/entity/CourseWish.java
  src/main/java/coursemaker/coursemaker/domain/wish/entity/DestinationWish.java
  src/main/java/coursemaker/coursemaker/domain/wish/service/CourseWishServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/wish/service/DestinationWishServiceImpl.java
Labels: Refactor

#299 코스, 공공데이터 도메인 로그 추가 작성 및 코스, 여행지 null 이라고 나오는 데이터 처리하기
  src/main/java/coursemaker/coursemaker/api/busanApi/service/BusanApiServiceImpl.java
  src/main/java/coursemaker/coursemaker/api/tourApi/service/TourApiServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/course/entity/TravelCourse.java
  src/main/java/coursemaker/coursemaker/domain/course/service/CourseServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/destination/dto/RequestDto.java
Labels: Feat, Refactor

#301 리뷰 기능 추가
  src/main/java/coursemaker/coursemaker/domain/review/controller/CourseReviewController.java
  src/main/java/coursemaker/coursemaker/domain/review/controller/DestinationReviewController.java
  src/main/java/coursemaker/coursemaker/domain/review/dto/ResponseCourseDto.java
  src/main/java/coursemaker/coursemaker/domain/review/dto/ResponseDestinationDto.java
  src/main/java/coursemaker/coursemaker/domain/review/repository/CourseReviewRepository.java
  src/main/java/coursemaker/coursemaker/domain/review/repository/DestinationReviewRepository.java
  src/main/java/coursemaker/coursemaker/domain/review/service/CourseReviewService.java
  src/main/java/coursemaker/coursemaker/domain/review/service/CourseReviewServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/review/service/DestinationReviewService.java
  src/main/java/coursemaker/coursemaker/domain/review/service/DestinationReviewServiceImpl.java
Labels: Feat

#302 Dev
  src/main/java/coursemaker/coursemaker/domain/review/controller/CourseReviewController.java
  src/main/java/coursemaker/coursemaker/domain/review/controller/DestinationReviewController.java
  src/main/java/coursemaker/coursemaker/domain/review/dto/RequestCourseDto.java
  src/main/java/coursemaker/coursemaker/domain/review/dto/RequestDestinationDto.java
  src/main/java/coursemaker/coursemaker/domain/review/dto/ResponseCourseDto.java
  src/main/java/coursemaker/coursemaker/domain/review/dto/ResponseDestinationDto.java
  src/main/java/coursemaker/coursemaker/domain/review/entity/CourseReview.java
  src/main/java/coursemaker/coursemaker/domain/review/entity/CourseReviewRecommendation.java
  src/main/java/coursemaker/coursemaker/domain/review/entity/DestinationReview.java
  src/main/java/coursemaker/coursemaker/domain/review/entity/DestinationReviewRecommendation.java
  src/main/java/coursemaker/coursemaker/domain/review/repository/CourseReviewRecommendationRepository.java
  src/main/java/coursemaker/coursemaker/domain/review/repository/CourseReviewRepository.java
  src/main/java/coursemaker/coursemaker/domain/review/repository/DestinationReviewRecommendationRepository.java
  src/main/java/coursemaker/coursemaker/domain/review/repository/DestinationReviewRepository.java
  src/main/java/coursemaker/coursemaker/domain/review/service/CourseReviewService.java
  src/main/java/coursemaker/coursemaker/domain/review/service/CourseReviewServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/review/service/DestinationReviewService.java
  src/main/java/coursemaker/coursemaker/domain/review/service/DestinationReviewServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/review/service/OrderBy.java
Labels: Feat, Refactor

#305 Refactor: 코스,여행지 리뷰 title 제거
  src/main/java/coursemaker/coursemaker/domain/review/controller/CourseReviewController.java
  src/main/java/coursemaker/coursemaker/domain/review/controller/DestinationReviewController.java
  src/main/java/coursemaker/coursemaker/domain/review/dto/RequestCourseDto.java
  src/main/java/coursemaker/coursemaker/domain/review/dto/RequestDestinationDto.java
  src/main/java/coursemaker/coursemaker/domain/review/dto/ResponseCourseDto.java
  src/main/java/coursemaker/coursemaker/domain/review/dto/ResponseDestinationDto.java
  src/main/java/coursemaker/coursemaker/domain/review/entity/CourseReview.java
  src/main/java/coursemaker/coursemaker/domain/review/entity/DestinationReview.java
  src/main/java/coursemaker/coursemaker/domain/review/repository/CourseReviewRepository.java
  src/main/java/coursemaker/coursemaker/domain/review/repository/DestinationReviewRepository.java
  src/main/java/coursemaker/coursemaker/domain/review/service/CourseReviewService.java
  src/main/java/coursemaker/coursemaker/domain/review/service/CourseReviewServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/review/service/DestinationReviewService.java
  src/main/java/coursemaker/coursemaker/domain/review/service/DestinationReviewServiceImpl.java
Labels: Refactor

#316 Feat: 여행지 apiContent 컬럼 추가
  src/main/java/coursemaker/coursemaker/domain/destination/dto/DestinationDto.java
  src/main/java/coursemaker/coursemaker/domain/destination/entity/Destination.java
Labels: Feat

#319 Refactor : 공공데이터 내용을 여행지 테이블의 content에서 apiContent으로 변경
  src/main/java/coursemaker/coursemaker/api/busanApi/service/BusanApiServiceImpl.java
  src/main/java/coursemaker/coursemaker/api/tourApi/service/TourApiServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/destination/dto/RequestDto.java
Labels: Refactor

#324 Refactor: 공공데이터 Tour Api 와 부산광역시 공공데이터 여행지 테이블에 저장 순서 바꾸기
  src/main/java/coursemaker/coursemaker/api/tourApi/dto/TourApiResponse.java
  src/main/java/coursemaker/coursemaker/api/tourApi/entity/TourApi.java
  src/main/java/coursemaker/coursemaker/api/tourApi/service/TourApiServiceImpl.java
Labels: Refactor

#330 Fix: 공공데이터 longtitude, latitude 바뀐거 수정
  src/main/java/coursemaker/coursemaker/api/tourApi/service/TourApiServiceImpl.java
Labels: Refactor
