Repository course-maker/Course-Maker-BE, pull requests merged in 2024-08, with the labels that each got.

#197 Dev
  src/main/java/coursemaker/coursemaker/api/busanApi/dto/BusanApiResponse.java
  src/main/java/coursemaker/coursemaker/api/busanApi/service/BusanApiServiceImpl.java
  src/main/java/coursemaker/coursemaker/api/tourApi/service/TourApiServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/destination/dto/DestinationDto.java
  src/main/java/coursemaker/coursemaker/domain/destination/entity/Destination.java
Labels: Feat

#198 #194 Refactor: 로그인 오류/토큰 만료시 상태코드 변경
  src/main/java/coursemaker/coursemaker/domain/auth/controller/AuthController.java
  src/main/java/coursemaker/coursemaker/domain/auth/dto/LoginedInfo.java
  src/main/java/coursemaker/coursemaker/domain/auth/exception/ExpiredAccessTokenException.java
  src/main/java/coursemaker/coursemaker/domain/auth/exception/ExpiredRefreshTokenException.java
  src/main/java/coursemaker/coursemaker/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/coursemaker/coursemaker/domain/auth/jwt/JwtProvider.java
  src/main/java/coursemaker/coursemaker/domain/auth/service/AuthService.java
  src/main/java/coursemaker/coursemaker/domain/tag/controller/TagController.java
  src/main/java/coursemaker/coursemaker/exception/ErrorCode.java
  src/main/java/coursemaker/coursemaker/exception/GlobalExceptionHandler.java
  src/main/java/coursemaker/coursemaker/util/LoginUser.java
Labels: Refactor

#212 Api 도메인 및 Course 도메인 스웨거 작성 및 Course 도메인 멤버 연결
  src/main/java/coursemaker/coursemaker/api/busanApi/controller/BusanApiController.java
  src/main/java/coursemaker/coursemaker/api/tourApi/controller/TourApiController.java
  src/main/java/coursemaker/coursemaker/domain/course/controller/CourseApiController.java
  src/main/java/coursemaker/coursemaker/domain/course/dto/TravelCourseResponse.java
Labels: Feat

#213 Feat: tourApi 데이터가 Destinaion DB로 저장될 때 별점을 0점으로 설정
  src/main/java/coursemaker/coursemaker/api/busanApi/service/BusanApiServiceImpl.java
  src/main/java/coursemaker/coursemaker/api/tourApi/service/TourApiServiceImpl.java
Labels: Feat

#219 Refactor: Course 도메인 로그인 하지 않으면 코스 조회 못하는 문제 개선
  src/main/java/coursemaker/coursemaker/domain/course/controller/CourseApiController.java
Labels: Refactor

#220 Feat: Course 도메인 멤버의 닉네임으로 코스 찾기 기능 구현
  src/main/java/coursemaker/coursemaker/domain/course/controller/CourseApiController.java
  src/main/java/coursemaker/coursemaker/domain/course/repository/TravelCourseRepository.java
  src/main/java/coursemaker/coursemaker/domain/course/service/CourseService.java
  src/main/java/coursemaker/coursemaker/domain/course/service/CourseServiceImpl.java
Labels: Feat

#232 Dev
  src/main/java/coursemaker/coursemaker/StubData.java
  src/main/java/coursemaker/coursemaker/api/busanApi/service/BusanApiServiceImpl.java
  src/main/java/coursemaker/coursemaker/api/tourApi/service/TourApiServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/course/controller/CourseApiController.java
  src/main/java/coursemaker/coursemaker/domain/course/service/CourseServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/destination/controller/DestinationController.java
  src/main/java/coursemaker/coursemaker/domain/destination/dto/RequestDto.java
  src/main/java/coursemaker/coursemaker/domain/destination/repository/DestinationRepository.java
  src/main/java/coursemaker/coursemaker/domain/destination/service/DestinationService.java
  src/main/java/coursemaker/coursemaker/domain/destination/service/DestinationServiceImpl.java
Labels: Feat

#236 공공데이터 태그 데이터 매핑
  src/main/java/coursemaker/coursemaker/StubData.java
  src/main/java/coursemaker/coursemaker/api/busanApi/dto/BusanApiResponse.java
  src/main/java/coursemaker/coursemaker/api/busanApi/entity/BusanApi.java
  src/main/java/coursemaker/coursemaker/api/busanApi/service/BusanApiServiceImpl.java
  src/main/java/coursemaker/coursemaker/api/tourApi/dto/TourApiResponse.java
  src/main/java/coursemaker/coursemaker/api/tourApi/entity/TourApi.java
  src/main/java/coursemaker/coursemaker/api/tourApi/service/TourApiServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/destination/dto/RequestDto.java
  src/main/java/coursemaker/coursemaker/domain/destination/entity/Destination.java
Labels: Feat

#240 Dev
  src/main/java/coursemaker/coursemaker/api/busanApi/service/BusanApiServiceImpl.java
  src/main/java/coursemaker/coursemaker/api/tourApi/service/TourApiServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/course/service/CourseDestinationService.java
  src/main/java/coursemaker/coursemaker/domain/destination/controller/DestinationController.java
  src/main/java/coursemaker/coursemaker/domain/destination/dto/DestinationDto.java
  src/main/java/coursemaker/coursemaker/domain/destination/dto/RequestDto.java
  src/main/java/coursemaker/coursemaker/domain/destination/entity/Destination.java
Labels: Refactor

#259 Refactor: 코스에서 별점 평균점수 조회 안 되던 문제 수정
  src/main/java/coursemaker/coursemaker/domain/course/dto/AddTravelCourseRequest.java
  src/main/java/coursemaker/coursemaker/domain/course/entity/TravelCourse.java
  src/main/java/coursemaker/coursemaker/domain/course/service/CourseServiceImpl.java
Labels: Refactor

#271 코스, 여행지에 찜, 리뷰 갯수 보이게 구현
  src/main/java/coursemaker/coursemaker/domain/course/controller/CourseApiController.java
  src/main/java/coursemaker/coursemaker/domain/course/dto/TravelCourseResponse.java
  src/main/java/coursemaker/coursemaker/domain/course/entity/TravelCourse.java
  src/main/java/coursemaker/coursemaker/domain/course/service/CourseDestinationService.java
  src/main/java/coursemaker/coursemaker/domain/destination/controller/DestinationController.java
  src/main/java/coursemaker/coursemaker/domain/destination/dto/DestinationDto.java
  src/main/java/coursemaker/coursemaker/domain/destination/entity/Destination.java
  src/main/java/coursemaker/coursemaker/domain/review/service/CourseReviewServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/review/service/DestinationReviewServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/wish/service/CourseWishService.java
  src/main/java/coursemaker/coursemaker/domain/wish/service/CourseWishServiceImpl.java
Labels: Feat

#277 Feat: 코스, 여행지 도메인 좋아요 보이게 구현
  src/main/java/coursemaker/coursemaker/domain/course/controller/CourseApiController.java
  src/main/java/coursemaker/coursemaker/domain/course/dto/TravelCourseResponse.java
  src/main/java/coursemaker/coursemaker/domain/course/entity/TravelCourse.java
  src/main/java/coursemaker/coursemaker/domain/course/service/CourseDestinationService.java
  src/main/java/coursemaker/coursemaker/domain/destination/controller/DestinationController.java
  src/main/java/coursemaker/coursemaker/domain/destination/dto/DestinationDto.java
  src/main/java/coursemaker/coursemaker/domain/destination/entity/Destination.java
Labels: Feat

#281 코스, 여행지 도메인 찜 했는지 여부 확인하는 기능 구현
  src/main/java/coursemaker/coursemaker/domain/course/controller/CourseApiController.java
  src/main/java/coursemaker/coursemaker/domain/course/dto/TravelCourseResponse.java
  src/main/java/coursemaker/coursemaker/domain/course/service/CourseDestinationService.java
  src/main/java/coursemaker/coursemaker/domain/destination/controller/DestinationController.java
  src/main/java/coursemaker/coursemaker/domain/destination/dto/DestinationDto.java
  src/main/java/coursemaker/coursemaker/domain/wish/service/CourseWishService.java
  src/main/java/coursemaker/coursemaker/domain/wish/service/CourseWishServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/wish/service/DestinationWishService.java
  src/main/java/coursemaker/coursemaker/domain/wish/service/DestinationWishServiceImpl.java
Labels: Feat

#284 여행지 도메인 소프트 딜리트로 개선 및 여행지, 코스 도메인 로그인 한 유저가 좋아요 여부 확인할 수 있게 구현
  src/main/java/coursemaker/coursemaker/api/busanApi/service/BusanApiServiceImpl.java
  src/main/java/coursemaker/coursemaker/api/tourApi/service/TourApiServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/course/controller/CourseApiController.java
  src/main/java/coursemaker/coursemaker/domain/course/dto/TravelCourseResponse.java
  src/main/java/coursemaker/coursemaker/domain/course/service/CourseDestinationService.java
  src/main/java/coursemaker/coursemaker/domain/course/service/CourseServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/destination/controller/DestinationController.java
  src/main/java/coursemaker/coursemaker/domain/destination/dto/DestinationDto.java
  src/main/java/coursemaker/coursemaker/domain/destination/entity/Destination.java
  src/main/java/coursemaker/coursemaker/domain/destination/repository/DestinationRepository.java
  src/main/java/coursemaker/coursemaker/domain/destination/service/DestinationServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/like/service/CourseLikeService.java
  src/main/java/coursemaker/coursemaker/domain/like/service/CourseLikeServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/like/service/DestinationLikeService.java
  src/main/java/coursemaker/coursemaker/domain/like/service/DestinationLikeServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/wish/service/CourseWishServiceImpl.java
  src/main/java/coursemaker/coursemaker/domain/wish/service/DestinationWishServiceImpl.java
Labels: Feat, Refactor
